// https://docs.expo.dev/guides/using-eslint/
//
// Committed deliberately. `expo lint` GENERATES this file when it is missing,
// so without it every run left an untracked eslint.config.js behind and each
// developer silently linted against whatever default their CLI version emitted.
//
// Keep `eslint` + `eslint-config-expo` in devDependencies. When they are
// absent `expo lint` REWRITES package.json to add them mid-run, so a fresh
// clone that ran lint came back with a dirty working tree — and the run itself
// still failed with "Cannot find module 'eslint'", because the newly installed
// module is not resolvable from the already-running process.
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: [
      'dist/*',
      '.expo/*',
      // Separate toolchains, deliberately outside repo TS/lint/test tooling:
      // Deno edge functions, and the Maestro E2E harness (node:*-only .mjs,
      // already excluded from tsconfig and jest).
      'supabase/functions/*',
      'e2e/*',
      // Native build output — generated by prebuild, gitignored.
      'ios/*',
      'android/*',
    ],
  },
  {
    // React Native renders to native text views, not HTML, so there is no
    // entity ambiguity for this rule to protect against. Enforcing it would
    // only obfuscate user-facing copy ("we&apos;ll" for "we'll") across the
    // onboarding screens. JSX does decode entities under RN — verified — so
    // this is a readability call, not a correctness one.
    rules: { 'react/no-unescaped-entities': 'off' },
  },
  {
    // Test-only framework patterns, not defects:
    //   import/first        — jest.mock() calls MUST precede imports; babel
    //                         hoists them and the repo relies on that ordering.
    //   no-require-imports  — require() inside jest.mock factories and
    //                         jest.requireActual is the documented pattern.
    //   display-name        — inline wrapper components in renderHook tests.
    files: ['src/__tests__/**', '__mocks__/**'],
    rules: {
      'import/first': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      'react/display-name': 'off',
    },
  },
]);
